-- Enable RLS for all core backend tables to prevent unauthorized Data API access
-- Service role operations (Edge Functions) bypass RLS automatically.

ALTER TABLE IF EXISTS public.calendars ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.market_data_pti ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.models ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.trade_opportunities ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.risk_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.idempotency_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.meta_api_retry_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.profit_take_requests ENABLE ROW LEVEL SECURITY;
